name: Build Project

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 12
  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
   
    - name: Build with Gradle
      run: ./gradlew build
