# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Build then deploy to DocFX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Generate DocFX readable Javadoc
      run: javadoc -encoding UTF-8 -docletpath ./libs/docfx-doclet-1.0-SNAPSHOT-jar-with-dependencies.jar -doclet com.microsoft.doclet.DocFxDoclet -sourcepath ./src/main/java -outputpath ./api -subpackages io.github.jtsshieh.persistentstorage:io.github.jtsshieh.persistentstorage.cached:io.github.jtsshieh.persistentstorage.queried
    - uses: nikeee/docfx-action@master
      name: Build Documentation
    - name: Publish Documentation to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: _site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
